### ISSUE TITLE
Path to "non-experimental" `rust_analyzer` support

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#704]
This issue tracks all the things required for promoting the `rust_analzyer` rule from "experimental".

## Tasks
- [ ] Remove the requirement for an explicit list of targets
- [ ] Setup a separate toolchain for gathering rustc sources

**Comment by UebelAndre** [comment]
The initial tasks are not set in stone, they're just a starting point. I'll update these with a complete list based on everyone's feedback.

cc @dfreese @illicitonion @djmarcin

**Comment by UebelAndre** [comment]
A lot of good insight can be found on https://github.com/bazelbuild/rules_rust/pull/505#issuecomment-780066923

**Comment by UebelAndre** [comment]
There's now docs for `rust-analyzer`: https://bazelbuild.github.io/rules_rust/rust_analyzer.html

**Comment by UebelAndre** [comment]
>     * [ ]  Setup a separate toolchain for gathering rustc sources

Maybe this is solved by https://github.com/bazelbuild/rules_rust/pull/737 ? It doesn't add a separate toolchain but allows for users to optionally download the the big bundle of sources. Which I think addresses the core issue here. It'd still probably be a usability improvement to have a separate toolchain so the flag would no longer e needed but I think this is more than sufficient for now.

**Comment by hlopko** [comment]
>  Remove the requirement for an explicit list of targets

IMHO that implies not having a rust analyzer target at all. I think this would be a valuable change. I imagine the workflow would then be:

1) `bazel run @rules_rust//tools:gen_rust_project -- //...`. This would invoke bazel behind the scenes with arguments after `--`. Great thing is that we can use `//...` or similar instead of explicitly listing all the top level targets.
2) the inner bazel would attach an aspect that will generate an output per rust library and build all those outputs
3) `gen_rust_project` would collect all those outputs and merge them together into `rust-project.json`

I admit I haven't yet fully read up on #505, if this was already proposed and rejected, just send me away.

**Comment by UebelAndre** [comment]
> I admit I haven't yet fully read up on #505, if this was already proposed and rejected, just send me away.

No, I think this is a great idea and wasn't something rejected (if I recall correctly). If you had the time to write that up I'd be happy to review 😄

**Comment by djmarcin** [comment]
Yep, this is the ideal. Initially I was trying to accomplish everything inside a bazel command, and it wasn't possible because there isn't the ability in bazel to have a single aggregate result of an invocation using `//...` (or something roughly equivalent to that statement). I don't think it's trivial to do outside of bazel either.

The difficulty is roughly that when you use the `rust_analyzer` target, bazel automatically has access to all the listed dependencies with all the right attached data. From there, it's easy to iterate over the depset and build up the output json file. When you run the `bazel build --aspect... //...` command, that depset is never created. To do this with the `gen_rust_project` binary, it will need to emulate that depset creation, probably by reading a bunch of individual output files from the bazel-out tree. I don't think there's any reason this is impossible, though.

**Comment by hlopko** [comment]
I see. One thing that can help with chasing down generated outputs is to run `bazel cquery` and parse its output in addition to `bazel build`

**Comment by GregBowyer** [comment]
I think two other things todo:

- [ ] Clion / Intellij AFAIK doesnt do anything with `rust-project.json` which made me have to bring back Cargo.toml. I think either the rust-plugin needs to catch up, or the bazel plugin in clion should learn about the aspect
- [ ] I seem to get unclear behaviour w.r.t `cfg(test)`, maybe we are misgenerating something?

**Comment by UebelAndre** [comment]
>     * Clion / Intellij AFAIK doesnt do anything with `rust-project.json` which made me have to bring back Cargo.toml. I think either the rust-plugin needs to catch up, or the bazel plugin in clion should learn about the aspect

I think it should be on Clion / Intellij to introduce support for `rust-project.json` since that's the recommendation from rust-analyzer in how you configure non-cargo based projects (see [docs](https://rust-analyzer.github.io/manual.html#non-cargo-based-projects)).

Though, does the Bazel clion plugin have rule specific behavior? That sounds interesting.

>     * I seem to get unclear behaviour w.r.t `cfg(test)`, maybe we are misgenerating something?

Interesting, can you give an example of the behavior you see now with `cfg(test)`?

**Comment by GregBowyer** [comment]
I think `cfg(test)` is a small tweak, right now if I have this

```python
rust_test(
   name = "some_test",
   crate = ":some",
   deps = [
      "//third_party/rust:proptest"
   ]
)
```

... `proptest` is invisible to the target as I think we dont merge the deps into the rust-project.json file.

For now I kinda ignore it, but I think that all `rust_` targets should be handled.

**Comment by GregBowyer** [comment]
For CLion I agree its on them (or someone) to support it, I am just calling it out because for us at $DAYJOB it broke people using intellij products when I removed all the extraneous `Cargo.toml`'s.

**Comment by djmarcin** [comment]
> I think `cfg(test)` is a small tweak, right now if I have this
> 
> ```python
> rust_test(
>    name = "some_test",
>    crate = ":some",
>    deps = [
>       "//third_party/rust:proptest"
>    ]
> )
> ```
> 
> ... `proptest` is invisible to the target as I think we dont merge the deps into the rust-project.json file.
> 
> For now I kinda ignore it, but I think that all `rust_` targets should be handled.

I think this means that `:some_test` is not listed as a target in your `rust_project` rule. If you list it, it should pick up proptest.

**Comment by GregBowyer** [comment]
no dice

```
Analyzing: target //:rust_analyzer (421 packages loaded, 101225 targets configured)
ERROR: /home/greg/work/cth/BUILD:111:14: in rust_analyzer rule //:rust_analyzer: non-test target '//:rust_analyzer' depends on testonly target '//noise/noise:noise_test' and doesn't have testonly attribute set
ERROR: Analysis of target '//:rust_analyzer' failed; build aborted: Analysis of target '//:rust_analyzer' failed
INFO: Elapsed time: 7.510s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (421 packages loaded, 126296 targets configured)
FAILED: Build did NOT complete successfully (421 packages loaded, 126296 targets configured)
', external/rules_rust/tools/rust_analyzer/main.rs:77:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by djmarcin** [comment]
I've started actively looking at refactoring the tools to not require a rust_project rule. I think I'll be able to get a PR out next week.

**Comment by GregBowyer** [comment]
Did we get further on this?

**Comment by hlopko** [comment]
Yup the new infra for Rust analyzer is submitted, there's no need to use the `rust_analyzer` rule anymore. For the wider topic of this issue, I don't know of anybody actively working on it.

**Comment by UebelAndre** [comment]
Perhaps https://github.com/JetBrains/bazel-bsp may be more useful to JetBrains users.

**Comment by UebelAndre** [comment]
https://github.com/bazelbuild/rules_rust/pull/1455 addresses the final check mark of wanting a separate toolchain for rust-src artifacts.

**Comment by nya3jp-google** [comment]
The doc still lists `rust_analyzer` rule as experimental. Do we want to update it?
https://bazelbuild.github.io/rules_rust/#experimental-rules
